name: CI Trabalho Individual
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Creating .env
        working-directory: ./library_back
        run: |
          echo POSTGRES_DB=library_db >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_PORT=5432 >> .env
          cat .env

      - name: Build backend
        working-directory: ./library_back
        run: docker-compose up -d

      - name: Build frontend
        working-directory: ./library_front
        run: docker-compose up -d

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Creating .env
        working-directory: ./library_back
        run: |
          echo POSTGRES_DB=library_db >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_PORT=5432 >> .env
          cat .env

      - name: Running tests
        working-directory: ./library_back
        run: docker compose -f docker-compose-test.yml up --abort-on-container-exit

  lint:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Creating .env
        working-directory: ./library_back
        run: |
          echo POSTGRES_DB=library_db >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_PORT=5432 >> .env
          cat .env

      - name: Instalacao flake
        working-directory: ./
        run: bash -c "pip install flake8"

      - name: Executando lint no backend
        working-directory: ./
        run: bash -c "flake8 --max-line-length 99 library_back"

      - name: Executando lint no frontend
        working-directory: ./
        run: bash -c "flake8 library_front"
