name: CD

on:
  workflow_run:
    workflows: CI
    types:
      - completed

jobs:
  deploy:
    name: Sending docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Backend image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: henriqueamorim20/trabalho-gces
          registry: docker.io
          directory: ./library_back
          dockerfile: ./library_back/Dockerfile
          tags: library_back,latest
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Frontend image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: henriqueamorim20/trabalho-gces
          registry: docker.io
          directory: ./library_front
          dockerfile: ./library_front/Dockerfile
          tags: library_front,latest
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}