name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Creating .env
        working-directory: ./library_back
        run: |
          echo POSTGRES_DB=library_db >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_HOST=db >> .env
          echo POSTGRES_PORT=5432 >> .env
          cat .env

      - name: Build backend
        working-directory: ./library_back
        run: docker-compose up -d

      - name: Build frontend
        working-directory: ./library_front
        run: docker-compose up -d